version: "3.8"

services:
  frontend:
      build:
        context: ./frontend
      ports:
        - "8080:8080"
      environment:
        - VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
        - VITE_PRODUCT_SERVICE_URL=${VITE_PRODUCT_SERVICE_URL}
        - VITE_ORDER_SERVICE_URL=${VITE_ORDER_SERVICE_URL}
        - VITE_MONGO_URL=mongodb://mongo:27017/ecommerce
        - JWT_SECRET=efrei_super_pass
      networks:
        - backend

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=efrei_super_pass 
    depends_on:
      - mongodb
    networks:
      - backend

  order-service:
    build:
      context: ./services/order-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=efrei_super_pass 
    depends_on:
      - mongodb
    networks:
      - backend

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=efrei_super_pass 
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data2:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    networks:
      - backend

volumes:
  mongo-data2:

networks:
  backend:
    driver: bridge
